version: "3.9"

services:
  nginx:
    depends_on:
      - php-pm
    volumes:
      - ./nginx/sites_available/ppm.conf:/etc/nginx/conf.d/default.conf

  php-pm:
    build:
      context: ./php/
      dockerfile: ppm/Dockerfile
    platform: linux/x86_64
    volumes:
      - ./app:/var/www/html
    depends_on:
      - database_server
    environment:
      - APP_URL=ppm-127-0-0-1.nip.io:8080
    healthcheck:
      test: curl --fail http://localhost:8080 || exit 1
      interval: 10s
      retries: 5
      start_period: 20s
      timeout: 10s
