version: "3.9"

services:
  nginx:
    depends_on:
      - php-fpm
    volumes:
      - ./nginx/sites_available/php-fpm.conf:/etc/nginx/conf.d/default.conf

  php-fpm:
    build:
      context: ./php/
      dockerfile: fpm/Dockerfile
    platform: linux/x86_64
    user: "1000:1000"
    volumes:
      - ./app:/var/www/html
      - ./php/z_custom.ini:/usr/local/etc/php/conf.d/z_custom.ini
      - ./php/fpm/z_custom.conf:/usr/local/etc/php-fpm.d/z_custom.conf
    environment:
      - APP_URL=fpm-127-0-0-1.nip.io:8080
