version: "3.9"

services:
  nginx:
    depends_on:
      - apache
    volumes:
      - ./nginx/sites_available/apache.conf:/etc/nginx/conf.d/default.conf

  apache:
    build:
      context: ./php/
      dockerfile: apache/Dockerfile
    container_name: apache
    user: "1000:1000"
    ports:
      - "8888:8888"
    environment:
      - APACHE_DOCUMENT_ROOT=/var/www/html/public
      - APP_URL=apache-127-0-0-1.nip.io:8080
    volumes:
      - ./app:/var/www/html
      - ./php/apache/vhost.conf:/etc/apache2/sites-available/000-default.conf
    depends_on:
      - database_server

