version: "3.9"

services:
  nginx:
    depends_on:
      - php-rr
    volumes:
      - ./nginx/sites_available/rr.conf:/etc/nginx/conf.d/default.conf

  php-rr:
    build:
      context: ./php/
      dockerfile: roadrunner/Dockerfile
    platform: linux/x86_64
    user: "1000:1000"
    volumes:
      - ./app:/app
    depends_on:
      - database_server
    environment:
      - APP_URL=rr-127-0-0-1.nip.io:8080
    healthcheck:
      test: curl --fail http://localhost:8000 || exit 1
      interval: 10s
      retries: 5
      start_period: 20s
      timeout: 10s
