version: "3.9"

services:
  nginx:
    container_name: nginx
    build:
      context: ./nginx/
    platform: linux/x86_64
    volumes:
      - ./app:/var/www/html
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "8080:80"

  database_server:
    image: mysql:5.7
    container_name: mysql
    environment:
      MYSQL_DATABASE: 'mydatabase'
      MYSQL_USER: 'myuser'
      MYSQL_PASSWORD: 'mystrongPassword'
      MYSQL_ROOT_PASSWORD: 'mysqlstrongpass'
      MYSQL_ROOT_HOST: '%'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - ./dbvolume:/var/lib/mysql
      - ./mysql/my.cnf:/etc/my.cnf

volumes:
  dbvolume:
  app:


